In [1]:
!unzip '/content/Amazon Product review.zip' -d "/content/"

Archive:  /content/Amazon Product review.zip
  inflating: /content/7817_1.csv

In [7]:
import pandas as pd

In [8]:
df=pd.read_csv('/content/7817_1.csv')
df

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,NaN,205 grams
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,4.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,NaN,205 grams
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1592,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,3.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,This is not the same remote that I got for my ...,I would be disappointed with myself if i produ...,NaN,NaN,GregAmandawith4,NaN,NaN,4 ounces
1593,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,1.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,I have had to change the batteries in this rem...,Battery draining remote!!!!,NaN,NaN,Amazon Customer,NaN,NaN,4 ounces
1594,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,1.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,"Remote did not activate, nor did it connect to...",replacing an even worse remote. Waste of time,NaN,NaN,Amazon Customer,NaN,NaN,4 ounces
1595,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,3.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,It does the job but is super over priced. I fe...,Overpriced,NaN,NaN,Meg Ashley,NaN,NaN,4 ounces
1596,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,1.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,I ordered this item to replace the one that no...,I am sending all of this crap back to amazon a...,NaN,NaN,DIANE K,NaN,NaN,4 ounces

In [9]:
df['reviews.rating'].value_counts()

reviews.rating
5.0    741
4.0    236
3.0    124
1.0     42
2.0     34
Name: count, dtype: int64

In [10]:
def sentiment(text):
  if text<3:
    return "Negative"
  elif text==3:
    return "Neutral"
  else:
    return "Positive"

In [11]:
df['reviews.rating']=df['reviews.rating'].apply(sentiment)
df

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,Positive,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,Positive,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,NaN,205 grams
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,Positive,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,Positive,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,Positive,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,NaN,205 grams
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1592,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,Neutral,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,This is not the same remote that I got for my ...,I would be disappointed with myself if i produ...,NaN,NaN,GregAmandawith4,NaN,NaN,4 ounces
1593,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,Negative,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,I have had to change the batteries in this rem...,Battery draining remote!!!!,NaN,NaN,Amazon Customer,NaN,NaN,4 ounces
1594,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,Negative,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,"Remote did not activate, nor did it connect to...",replacing an even worse remote. Waste of time,NaN,NaN,Amazon Customer,NaN,NaN,4 ounces
1595,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,Neutral,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,It does the job but is super over priced. I fe...,Overpriced,NaN,NaN,Meg Ashley,NaN,NaN,4 ounces
1596,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,Negative,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,I ordered this item to replace the one that no...,I am sending all of this crap back to amazon a...,NaN,NaN,DIANE K,NaN,NaN,4 ounces

In [40]:
df2=df[['reviews.text', 'reviews.rating']].copy()

In [41]:
df2

                                           reviews.text reviews.rating
0     I initially had trouble deciding between the p...       Positive
1     Allow me to preface this with a little history...       Positive
2     I am enjoying it so far. Great for reading. Ha...       Positive
3     I bought one of the first Paperwhites and have...       Positive
4     I have to say upfront - I don't like coroporat...       Positive
...                                                 ...            ...
1592  This is not the same remote that I got for my ...        Neutral
1593  I have had to change the batteries in this rem...       Negative
1594  Remote did not activate, nor did it connect to...       Negative
1595  It does the job but is super over priced. I fe...        Neutral
1596  I ordered this item to replace the one that no...       Negative

[1597 rows x 2 columns]

In [42]:
df2['reviews.text']=df2['reviews.text'].str.lower()

In [43]:
df2

                                           reviews.text reviews.rating
0     i initially had trouble deciding between the p...       Positive
1     allow me to preface this with a little history...       Positive
2     i am enjoying it so far. great for reading. ha...       Positive
3     i bought one of the first paperwhites and have...       Positive
4     i have to say upfront - i don't like coroporat...       Positive
...                                                 ...            ...
1592  this is not the same remote that i got for my ...        Neutral
1593  i have had to change the batteries in this rem...       Negative
1594  remote did not activate, nor did it connect to...       Negative
1595  it does the job but is super over priced. i fe...        Neutral
1596  i ordered this item to replace the one that no...       Negative

[1597 rows x 2 columns]

In [44]:
import string
def remove_punc(text):
  return text.translate(str.maketrans('','', string.punctuation))

In [45]:
df2['reviews.text']=df2['reviews.text'].apply(remove_punc)
df2

                                           reviews.text reviews.rating
0     i initially had trouble deciding between the p...       Positive
1     allow me to preface this with a little history...       Positive
2     i am enjoying it so far great for reading had ...       Positive
3     i bought one of the first paperwhites and have...       Positive
4     i have to say upfront  i dont like coroporate ...       Positive
...                                                 ...            ...
1592  this is not the same remote that i got for my ...        Neutral
1593  i have had to change the batteries in this rem...       Negative
1594  remote did not activate nor did it connect to ...       Negative
1595  it does the job but is super over priced i fee...        Neutral
1596  i ordered this item to replace the one that no...       Negative

[1597 rows x 2 columns]

In [46]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))

    words = text.split()

    filtered_words = [
        word for word in words
        if word.lower() not in stop_words
    ]

    return " ".join(filtered_words)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [47]:
df2['reviews.text']=df2['reviews.text'].apply(remove_stopwords)
df2

                                           reviews.text reviews.rating
0     initially trouble deciding paperwhite voyage r...       Positive
1     allow preface little history casual reader own...       Positive
2     enjoying far great reading original fire since...       Positive
3     bought one first paperwhites pleased constant ...       Positive
4     say upfront dont like coroporate hermetically ...       Positive
...                                                 ...            ...
1592  remote got alexaecho doesnt control volume thi...        Neutral
1593  change batteries remote twice per month since ...       Negative
1594  remote activate connect boxa poorly designed r...       Negative
1595  job super priced feel like offer replacement r...        Neutral
1596  ordered item replace one longer works directio...       Negative

[1597 rows x 2 columns]

In [48]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [49]:
wl=WordNetLemmatizer()
def lemmatize(text):
  text=text.split()
  text=[wl.lemmatize(word, pos='v') for word in text]
  return ' '.join(text)

In [50]:
df2['reviews.text']=df2['reviews.text'].apply(lemmatize)
df2

                                           reviews.text reviews.rating
0     initially trouble decide paperwhite voyage rev...       Positive
1     allow preface little history casual reader own...       Positive
2     enjoy far great read original fire since 2012 ...       Positive
3     buy one first paperwhites please constant comp...       Positive
4     say upfront dont like coroporate hermetically ...       Positive
...                                                 ...            ...
1592  remote get alexaecho doesnt control volume thi...        Neutral
1593  change batteries remote twice per month since ...       Negative
1594  remote activate connect boxa poorly design rem...       Negative
1595  job super price feel like offer replacement re...        Neutral
1596  order item replace one longer work directions ...       Negative

[1597 rows x 2 columns]

In [53]:
x=df2['reviews.text']
y=df2['reviews.rating']

In [56]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
y=le.fit_transform(y)
y

array([2, 2, 2, ..., 0, 1, 0])

In [57]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.25, random_state=5)

# **First Approach: TFIDF + Logistic Regression**

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [64]:
tf=TfidfVectorizer()

xtrain=tf.fit_transform(x_train).toarray()
xtest=tf.transform(x_test).toarray()

In [65]:
xtrain

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [66]:
from sklearn.linear_model import LogisticRegression

lr=LogisticRegression()

In [67]:
lr.fit(xtrain, y_train)

LogisticRegression()

In [68]:
ypred=lr.predict(xtest)

In [69]:
from sklearn.metrics import accuracy_score

In [71]:
print(accuracy_score(ypred,y_test)*100)

89.25

# **Second Approach: Word2vec + Random Forest**

In [72]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.0)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 32.1 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [75]:
import gensim
from gensim.utils import simple_preprocess
from nltk import sent_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [76]:
data=[]

for word in df2['reviews.text']:
  rs=sent_tokenize(word)
  for s in rs:
    data.append(simple_preprocess(s))

In [77]:
data

[['initially',
  'trouble',
  'decide',
  'paperwhite',
  'voyage',
  'review',
  'less',
  'say',
  'thing',
  'paperwhite',
  'great',
  'spend',
  'money',
  'go',
  'friends',
  'own',
  'end',
  'buy',
  'paperwhite',
  'basis',
  'model',
  'ppi',
  'dollar',
  'jump',
  'turn',
  'pricey',
  'voyage',
  'page',
  'press',
  'isnt',
  'always',
  'sensitive',
  'fine',
  'specific',
  'set',
  'dont',
  'need',
  'auto',
  'light',
  'adjustmentits',
  'week',
  'love',
  'paperwhite',
  'regret',
  'touch',
  'screen',
  'receptive',
  'easy',
  'use',
  'keep',
  'light',
  'specific',
  'set',
  'regardless',
  'time',
  'day',
  'case',
  'hard',
  'change',
  'set',
  'either',
  'youll',
  'change',
  'light',
  'level',
  'certain',
  'time',
  'day',
  'every',
  'readingalso',
  'glad',
  'go',
  'international',
  'ship',
  'option',
  'amazon',
  'extra',
  'expense',
  'delivery',
  'time',
  'track',
  'didnt',
  'need',
  'worry',
  'customs',
  'may',
  'use',
  'third',
  'party',
  'ship',
  'service'],
 ['allow',
  'preface',
  'little',
  'history',
  'casual',
  'reader',
  'own',
  'nook',
  'simple',
  'touch',
  'ive',
  'read',
  'harry',
  'potter',
  'series',
  'girl',
  'dragon',
  'tattoo',
  'series',
  'brave',
  'new',
  'world',
  'key',
  'title',
  'fair',
  'say',
  'nook',
  'get',
  'much',
  'use',
  'many',
  'others',
  'may',
  'get',
  'theirsfast',
  'forward',
  'today',
  'full',
  'week',
  'new',
  'kindle',
  'paperwhite',
  'admit',
  'im',
  'love',
  'kindle',
  'read',
  'let',
  'relate',
  'review',
  'love',
  'read',
  'back',
  'kindle',
  'investment',
  'experience',
  'receive',
  'buy',
  'kindle',
  'simply',
  'pay',
  'screen',
  'entire',
  'experience',
  'include',
  'buy',
  'amazoni',
  'read',
  'hunger',
  'game',
  'trilogy',
  'shall',
  'move',
  'onto',
  'divergent',
  'series',
  'soon',
  'thing',
  'nook',
  'hinder',
  'past',
  'years',
  'never',
  'inspire',
  'pick',
  'get',
  'hand',
  'dive',
  'never',
  'feel',
  'oh',
  'man',
  'read',
  'thing',
  'awesome',
  'however',
  'paperwhite',
  'feel',
  'desire',
  'back',
  'simply',
  'adore',
  'kindle',
  'consider',
  'purchase',
  'one',
  'stop',
  'think',
  'simply',
  'go',
  'full',
  'week',
  'download',
  'book',
  'ton',
  'read',
  'still',
  'half',
  'battery',
  'leave',
  'wellmake',
  'happy',
  'inspire',
  'reader',
  'inside'],
 ['enjoy',
  'far',
  'great',
  'read',
  'original',
  'fire',
  'since',
  'fire',
  'use',
  'make',
  'eye',
  'hurt',
  'read',
  'long',
  'havent',
  'experience',
  'paperwhite',
  'yet'],
 ['buy',
  'one',
  'first',
  'paperwhites',
  'please',
  'constant',
  'companion',
  'suppose',
  'ive',
  'read',
  'average',
  'book',
  'every',
  'three',
  'days',
  'past',
  'however',
  'many',
  'years',
  'wouldnt',
  'give',
  'youd',
  'pry',
  'cold',
  'dead',
  'fingersfor',
  'sundry',
  'logistical',
  'reason',
  'ive',
  'also',
  'make',
  'good',
  'use',
  'amazons',
  'kindle',
  'app',
  'iphone',
  'paperwhite',
  'screen',
  'naturally',
  'cool',
  'usability',
  'deliver',
  'work',
  'well',
  'attractions',
  'companion',
  'kindleof',
  'course',
  'aspects',
  'paperwhite',
  'would',
  'like',
  'critique',
  'ah',
  'know',
  'come',
  'somewhere',
  'didnt',
  'youas',
  'member',
  'bookbub',
  'get',
  'daily',
  'list',
  'alert',
  'book',
  'deal',
  'choose',
  'genres',
  'take',
  'many',
  'however',
  'ive',
  'find',
  'even',
  'best',
  'world',
  'cant',
  'keep',
  'days',
  'seem',
  'every',
  'book',
  'read',
  'ive',
  'buy',
  'two',
  'theres',
  'much',
  'good',
  'stuff',
  'accumulative',
  'effect',
  'number',
  'book',
  'actually',
  'paperwhite',
  'creep',
  'ever',
  'upward',
  'time',
  'with',
  'mind',
  'ive',
  'notice',
  'pageturning',
  'remain',
  'exactly',
  'every',
  'action',
  'kindle',
  'become',
  'positively',
  'glacial',
  'slow',
  'slow',
  'think',
  'malfunction',
  'general',
  'consensus',
  'appear',
  'expect',
  'one',
  'many',
  'book',
  'download',
  'onto',
  'kindle',
  'begin',
  'behave',
  'flakey',
  'manner',
  'drive',
  'mad',
  'amazon',
  'state',
  'hold',
  'thousands',
  'book',
  'believe',
  'figure',
  'would',
  'need',
  'second',
  'paperwhite',
  'read',
  'im',
  'wait',
  'action',
  'complete',
  'first',
  'oneread'],
 ['say',
  'upfront',
  'dont',
  'like',
  'coroporate',
  'hermetically',
  'close',
  'stuff',
  'like',
  'anything',
  'apple',
  'case',
  'amazon',
  'like',
  'devices',
  'put',
  'anything',
  'want',
  'use',
  'buti',
  'fairly',
  'happy',
  'user',
  'nook',
  'touch',
  'several',
  'years',
  'couldnt',
  'use',
  'functionalities',
  'since',
  'live',
  'serbia',
  'lose',
  'nook',
  'since',
  'devices',
  'actually',
  'fully',
  'use',
  'serbia',
  'buy',
  'book',
  'use',
  'online',
  'capabilities',
  'except',
  'kindle',
  'since',
  'one',
  'except',
  'amazon',
  'ship',
  'serbia',
  'since',
  'ive',
  'actually',
  'happy',
  'amazon',
  'customer',
  'since',
  'friends',
  'account',
  'since',
  'since',
  'kindle',
  'definitely',
  'best',
  'technology',
  'buy',
  'itso',
  'read',
  'many',
  'review',
  'screenlight',
  'paperwhite',
  'similar',
  'devices',
  'problem',
  'mine',
  'light',
  'disperse',
  'fine',
  'except',
  'black',
  'blotch',
  'maybe',
  'see',
  'picture',
  'bottom',
  'screen',
  'actually',
  'shadow',
  'black',
  'plastic',
  'case',
  'thus',
  'cant',
  'really',
  'avoid',
  'see',
  'picture',
  'without',
  'light',
  'blotch',
  'light',
  'outthe',
  'paperwhites',
  'screen',
  'marvelous',
  'ppi',
  'touchscreen',
  'work',
  'fine',
  'store',
  'work',
  'serbia',
  'two',
  'days',
  'ive',
  'use',
  'im',
  'happy',
  'guyi',
  'get',
  'hang',
  'make',
  'sideloaded',
  'book',
  'behave',
  'least',
  'almost',
  'like',
  'amazon',
  'book',
  'thats',
  'fine',
  'thats',
  'one',
  'thing',
  'id',
  'like',
  'see',
  'amazon',
  'future',
  'upgrade',
  'make',
  'kindle',
  'treat',
  'sideloaded',
  'book',
  'like',
  'ones',
  'buy',
  'directly',
  'share',
  'funcion',
  'quote',
  'goodreads',
  'enable',
  'onthe',
  'size',
  'perfect',
  'sit',
  'well',
  'hand',
  'light',
  'doesnt',
  'hurt',
  'eye',
  'dark',
  'like',
  'light',
  'tab',
  'package',
  'fine',
  'problems',
  'remain',
  'see',
  'battery',
  'lifeso',
  'far',
  'recommend'],
 ['previous',
  'kindle',
  'dx',
  'second',
  'kindle',
  'years',
  'love',
  'form',
  'factor',
  'miss',
  'physical',
  'button',
  'page',
  'turn',
  'glitch',
  'software',
  'though',
  'use',
  'english',
  'interface',
  'occasionally',
  'would',
  'like',
  'translate',
  'word',
  'traditional',
  'chinese',
  'however',
  'seem',
  'traditional',
  'chinese',
  'character',
  'cannot',
  'display',
  'correctly',
  'become',
  'small',
  'box',
  'simplify',
  'chinese',
  'character',
  'display',
  'correctly',
  'though'],
 ['allow',
  'preface',
  'little',
  'history',
  'casual',
  'reader',
  'own',
  'nook',
  'simple',
  'touch',
  'ive',
  'read',
  'harry',
  'potter',
  'series',
  'girl',
  'dragon',
  'tattoo',
  'series',
  'brave',
  'new',
  'world',
  'key',
  'title',
  'fair',
  'say',
  'nook',
  'get',
  'much',
  'use',
  'many',
  'others',
  'may',
  'get',
  'theirsfast',
  'forward',
  'today',
  'full',
  'week',
  'new',
  'kindle',
  'paperwhite',
  'admit',
  'im',
  'love',
  'kindle',
  'read',
  'let',
  'relate',
  'review',
  'love',
  'read',
  'back',
  'kindle',
  'investment',
  'experience',
  'receive',
  'buy',
  'kindle',
  'simply',
  'pay',
  'screen',
  'entire',
  'experience',
  'include',
  'buy',
  'amazoni',
  'read',
  'hunger',
  'game',
  'trilogy',
  'shall',
  'move',
  'onto',
  'divergent',
  'series',
  'soon',
  'thing',
  'nook',
  'hinder',
  'past',
  'years',
  'never',
  'inspire',
  'pick',
  'get',
  'hand',
  'dive',
  'never',
  'feel',
  'oh',
  'man',
  'read',
  'thing',
  'awesome',
  'however',
  'paperwhite',
  'feel',
  'desire',
  'back',
  'simply',
  'adore',
  'kindle',
  'consider',
  'purchase',
  'one',
  'stop',
  'think',
  'simply',
  'go',
  'full',
  'week',
  'download',
  'book',
  'ton',
  'read',
  'still',
  'half',
  'battery',
  'leave',
  'wellmake',
  'happy',
  'inspire',
  'reader',
  'inside'],
 ['get',
  'mine',
  'right',
  'look',
  'previous',
  'generation',
  'except',
  'kindle',
  'logo',
  'black',
  'time',
  'feel',
  'little',
  'heavier',
  'screen',
  'little',
  'warmer',
  'tone',
  'previous',
  'one',
  'resolution',
  'much',
  'better',
  'ppi',
  'definitely',
  'obvious',
  'new',
  'font',
  'worth',
  'moneytotally',
  'recommend',
  'book',
  'loverill',
  'give',
  'star',
  'instead',
  'use',
  'cooler',
  'screen',
  'im',
  'sure',
  'ill',
  'get',
  'use',
  'one',
  'soon'],
 ['initially',
  'trouble',
  'decide',
  'paperwhite',
  'voyage',
  'review',
  'less',
  'say',
  'thing',
  'paperwhite',
  'great',
  'spend',
  'money',
  'go',
  'friends',
  'own',
  'end',
  'buy',
  'paperwhite',
  'basis',
  'model',
  'ppi',
  'dollar',
  'jump',
  'turn',
  'pricey',
  'voyage',
  'page',
  'press',
  'isnt',
  'always',
  'sensitive',
  'fine',
  'specific',
  'set',
  'dont',
  'need',
  'auto',
  'light',
  'adjustmentits',
  'week',
  'love',
  'paperwhite',
  'regret',
  'touch',
  'screen',
  'receptive',
  'easy',
  'use',
  'keep',
  'light',
  'specific',
  'set',
  'regardless',
  'time',
  'day',
  'case',
  'hard',
  'change',
  'set',
  'either',
  'youll',
  'change',
  'light',
  'level',
  'certain',
  'time',
  'day',
  'every',
  'readingalso',
  'glad',
  'go',
  'international',
  'ship',
  'option',
  'amazon',
  'extra',
  'expense',
  'delivery',
  'time',
  'track',
  'didnt',
  'need',
  'worry',
  'customs',
  'may',
  'use',
  'third',
  'party',
  'ship',
  'service'],
 ['enjoy',
  'far',
  'great',
  'read',
  'original',
  'fire',
  'since',
  'fire',
  'use',
  'make',
  'eye',
  'hurt',
  'read',
  'long',
  'havent',
  'experience',
  'paperwhite',
  'yet'],
 ['review',
  'wife',
  'perfect',
  'thing',
  'new',
  'mommy',
  'love',
  'read',
  'book',
  'soon',
  'baby',
  'girl',
  'stop',
  'read',
  'novels',
  'give',
  'baby',
  'full',
  'attention',
  'much',
  'time',
  'spend',
  'lay',
  'bed',
  'side',
  'baby',
  'feed',
  'especially',
  'prior',
  'months',
  'feed',
  'take',
  'long',
  'minutes',
  'mention',
  'cluster',
  'feed',
  'growth',
  'spurt',
  'book',
  'question',
  'sooo',
  'tire',
  'hold',
  'new',
  'kindle',
  'solution',
  'light',
  'easy',
  'disinfect',
  'use',
  'baby',
  'wipe',
  'case',
  'whenever',
  'feel',
  'like',
  'clean',
  'enough',
  'go',
  'bed',
  'baby',
  'dont',
  'need',
  'keep',
  'finger',
  'middle',
  'page',
  'keep',
  'close',
  'know',
  'meanand',
  'reason',
  'much',
  'easier',
  'go',
  'book',
  'kindle',
  'compare',
  'actual',
  'book',
  'never',
  'think',
  'id',
  'convert',
  'kindle',
  'culture'],
 ['new',
  'kindle',
  'paperwhite',
  'come',
  'usa',
  'small',
  'town',
  'sweden',
  'five',
  'days',
  'payment',
  'tax',
  'customs',
  'handle',
  'amazon',
  'up',
  'square',
  'think',
  'everyone',
  'sit',
  'home',
  'day',
  'receive',
  'day',
  'earlieri',
  'please',
  'ereader',
  'easy',
  'eye',
  'comfortable',
  'hold',
  'one',
  'hand',
  'even',
  'buy',
  'many',
  'book',
  'amazon',
  'also',
  'want',
  'read',
  'book',
  'epub',
  'format',
  'positive',
  'surprise',
  'easy',
  'convert',
  'epub',
  'format',
  'amazons',
  'format',
  'use',
  'program',
  'calibre',
  'send',
  'book',
  'attachment',
  'email',
  'kindle',
  'quick',
  'easy'],
 ['enjoy',
  'far',
  'great',
  'read',
  'original',
  'fire',
  'since',
  'fire',
  'use',
  'make',
  'eye',
  'hurt',
  'read',
  'long',
  'havent',
  'experience',
  'paperwhite',
  'yet'],
 ['older',
  'model',
  'could',
  'text',
  'speech',
  'one',
  'hasnt',
  'like',
  'smaller',
  'size',
  'buy',
  'different',
  'cover',
  'still',
  'get',
  'use',
  'shelf',
  'quite',
  'different',
  'year',
  'old',
  'modelpaper',
  'white',
  'nice',
  'read'],
 ['review',
  'kindle',
  'paperwhite',
  'launch',
  'july',
  'essentially',
  'previous',
  'kindle',
  'paperwhite',
  'fantastic',
  'upgrade',
  'dpi',
  'screen',
  'memory',
  'storage',
  'terrific',
  'read',
  'device',
  'review',
  'aim',
  'describe',
  'product',
  'compare',
  'kindle',
  'devices',
  'available',
  'help',
  'choose',
  'best',
  'one',
  'youbefore',
  'start',
  'ive',
  'notice',
  'several',
  'complain',
  'kindle',
  'support',
  'epub',
  'format',
  'use',
  'canadian',
  'public',
  'libraries',
  'dont',
  'put',
  'theres',
  'solution',
  'frequently',
  'ask',
  'question',
  'section',
  'belowthis',
  'review',
  'break',
  'section',
  'skip',
  'less',
  'interest',
  'bits',
  'youre',
  'hurry',
  'ive',
  'include',
  'summary',
  'start',
  'frequently',
  'ask',
  'question',
  'section',
  'endsummary',
  'read',
  'book',
  'store',
  'book',
  'take',
  'entire',
  'library',
  'away',
  'holiday',
  'buy',
  'book',
  'browse',
  'amazon',
  'kindle',
  'store',
  'buy',
  'book',
  'wifi',
  'connection',
  'borrow',
  'book',
  'use',
  'kindle',
  'owners',
  'library',
  'borrow',
  'one',
  'book',
  'amazon',
  'prime',
  'membership',
  'share',
  'book',
  'use',
  'amazon',
  'family',
  'library',
  'link',
  'two',
  'amazon',
  'account',
  'four',
  'children',
  'share',
  'book',
  'entire',
  'family',
  'highlight',
  'section',
  'use',
  'touch',
  'screen',
  'highlight',
  'particulary',
  'interest',
  'line',
  'several',
  'people',
  'highlight',
  'section',
  'thats',
  'also',
  'indicate',
  'record',
  'bookmark',
  'come',
  'back',
  'later',
  'read',
  'book',
  'kindle',
  'continue',
  'smartphone',
  'tablet',
  'computer',
  'jump',
  'last',
  'know',
  'position',
  'look',
  'word',
  'record',
  'vocabulary',
  'builder',
  'track',
  'character',
  'appearance',
  'throughout',
  'book',
  'use',
  'ray',
  'feature',
  'read',
  'weeks',
  'without',
  'need',
  'recharge',
  'typically',
  'weeks',
  'share',
  'book',
  'multiple',
  'kindle',
  'account',
  'family',
  'share',
  'access',
  'every',
  'book',
  'youve',
  'ever',
  'own',
  'cloud',
  'available',
  'download',
  'within',
  'second',
  'wifi',
  'gwhat',
  'devices',
  'availableas',
  'july',
  'amazon',
  'follow',
  'kindle',
  'devices',
  'sale',
  'kindle',
  'around',
  'cdn',
  'kindle',
  'paperwhite',
  'th',
  'generation',
  'dpi',
  'launch',
  'october',
  'around',
  'cdn',
  'new',
  'kindle',
  'paperwhite',
  'th',
  'gen',
  'dpi',
  'launch',
  'july',
  'around',
  'cdn',
  'kindle',
  'voyger',
  'around',
  'us',
  'doesnt',
  'seem',
  'sale',
  'amazon',
  'canada',
  'kindle',
  'fire',
  'colour',
  'tablet',
  'computers',
  'around',
  'cdn',
  'so',
  'youre',
  'face',
  'devices',
  'plus',
  'additional',
  'options',
  'buy',
  'heres',
  'quick',
  'summary',
  'order',
  'cost',
  'entry',
  'level',
  'kindle',
  'entry',
  'level',
  'black',
  'white',
  'eink',
  'book',
  'reader',
  'inch',
  'touch',
  'screen',
  'enough',
  'storage',
  'hold',
  'thousands',
  'book',
  'battery',
  'last',
  'around',
  'weeksa',
  'terrific',
  'device',
  'read',
  'book',
  'worthy',
  'contender',
  'technically',
  'mind',
  'ghz',
  'processor',
  'gb',
  'memory',
  'eink',
  'display',
  'essentially',
  'mean',
  'black',
  'white',
  'fantastic',
  'read',
  'even',
  'bright',
  'sunlight',
  'require',
  'little',
  'power',
  'hence',
  'battery',
  'last',
  'weeks',
  'instead',
  'hours',
  'new',
  'kindle',
  'paperwhite',
  'launch',
  'really',
  'upgrade',
  'add',
  'supersharp',
  'display',
  'pixels',
  'per',
  'inch',
  'top',
  'range',
  'voyage',
  'high',
  'resolution',
  'screen',
  'provide',
  'crisp',
  'text',
  'please',
  'eye',
  'battery',
  'life',
  'reduce',
  'weeks',
  'original',
  'paperwhite',
  'weeks',
  'still',
  'long',
  'timecompared',
  'exist',
  'paperwhite',
  'also',
  'include',
  'double',
  'memory',
  'mean',
  'faster',
  'slicker',
  'new',
  'bookerly',
  'font',
  'plus',
  'better',
  'presentation',
  'fonts',
  'screenif',
  'exist',
  'paperwhite',
  'probably',
  'worth',
  'upgrade',
  'however',
  'prior',
  'device',
  'youll',
  'notice',
  'huge',
  'leap',
  'screen',
  'quality',
  'contrast',
  'performance',
  'voyage',
  'far',
  'expensive',
  'paperwhite',
  'thinner',
  'lighter',
  'quality',
  'feel',
  'screen',
  'flush',
  'ereader',
  'body',
  'make',
  'look',
  'like',
  'tablet',
  'keep',
  'dirt',
  'get',
  'catch',
  'edge',
  'back',
  'soft',
  'touch',
  'plastic',
  'finish',
  'feel',
  'lovely',
  'hand',
  'new',
  'page',
  'press',
  'button',
  'side',
  'turn',
  'page',
  'button',
  'press',
  'theres',
  'gentle',
  'vibration',
  'feedback',
  'nice',
  'touch',
  'gb',
  'storage',
  'paperwhite',
  'similar',
  'battery',
  'last',
  'around',
  'weeks',
  'single',
  'chargealthough',
  'sharp',
  'dpi',
  'screen',
  'paperwhite',
  'backlight',
  'include',
  'ambient',
  'light',
  'sensor',
  'automatically',
  'adjust',
  'different',
  'light',
  'condition',
  'mean',
  'read',
  'dark',
  'automatically',
  'adjust',
  'brightness',
  'doesnt',
  'look',
  'bright',
  'addition',
  'youll',
  'find',
  'switch',
  'room',
  'light',
  'eye',
  'naturally',
  'become',
  'accustom',
  'darkness',
  'compensate',
  'voyage',
  'automatically',
  'soften',
  'light',
  'slightly',
  'lovely',
  'example',
  'attention',
  'detail',
  'premium',
  'device',
  'kindle',
  'fire',
  'tablet',
  'computer',
  'kindle',
  'fire',
  'range',
  'different',
  'beast',
  'rest',
  'kindle',
  'range',
  'similar',
  'apple',
  'ipad',
  'mini',
  'high',
  'resolution',
  'screen',
  'fast',
  'processor',
  'lot',
  'memory',
  'colour',
  'screen',
  'much',
  'shorter',
  'battery',
  'life',
  'hours',
  'rather',
  'weeks',
  'although',
  'read',
  'book',
  'fire',
  'use',
  'amazon',
  'kindle',
  'app',
  'youll',
  'find',
  'kindle',
  'sharp',
  'black',
  'white',
  'screen',
  'far',
  'like',
  'read',
  'physical',
  'book',
  'youll',
  'find',
  'produce',
  'less',
  'eye',
  'strain',
  'whereas',
  'tablet',
  'computer',
  'better',
  'suit',
  'surf',
  'web',
  'watch',
  'videos',
  'read',
  'email',
  'kindle',
  'dedicate',
  'book',
  'reader',
  'deviceunlike',
  'kindle',
  'fire',
  'produce',
  'light',
  'blue',
  'end',
  'spectrum',
  'mean',
  'may',
  'make',
  'harder',
  'sleep',
  'paperwhite',
  'voyage',
  'also',
  'ave',
  'advantage',
  'soft',
  'white',
  'backlight',
  'far',
  'suit',
  'read',
  'bed',
  'wont',
  'example',
  'wake',
  'partner',
  'read',
  'darkfinally',
  'unlike',
  'rest',
  'kindle',
  'range',
  'fire',
  'almost',
  'useless',
  'bright',
  'sunlight',
  'fine',
  'everyday',
  'use',
  'less',
  'useful',
  'holiday',
  'kindle',
  'range',
  'devices',
  'perfect',
  'take',
  'away',
  'holiday',
  'carry',
  'thousands',
  'book',
  'pleasure',
  'read',
  'even',
  'bright',
  'sunlightwhat',
  'options',
  'havehaving',
  'decide',
  'upon',
  'model',
  'kindle',
  'paperwhite',
  'voyage',
  'fire',
  'next',
  'decision',
  'around',
  'special',
  'offer',
  'ie',
  'advert',
  'wifi',
  'issue',
  'advert',
  'kindle',
  'appear',
  'screen',
  'screen',
  'saver',
  'distractingthe',
  'option',
  'difficult',
  'question',
  'effectively',
  'mean',
  'use',
  'kindle',
  'buy',
  'download',
  'book',
  'overtheair',
  'instead',
  'home',
  'near',
  'wifi',
  'hotspot',
  'personally',
  'go',
  'wifi',
  'model',

In [78]:
model=gensim.models.Word2Vec(
    window=5
)

In [79]:
model.build_vocab(data)

In [81]:
model.train(data, total_examples=model.corpus_count, epochs=model.epochs)

(568440, 671660)

In [104]:
import numpy as np
def doc_vector(doc):
  doc=[word for word in doc.split() if word in model.wv.index_to_key]
  if len(doc) == 0:
        return np.zeros(model.vector_size)

  return np.mean(model.wv[doc], axis=0)

In [105]:
x1=[]
for doc in df2['reviews.text'].values:
  x1.append(doc_vector(doc))

In [103]:
#sum(df2['reviews.text'].str.strip() == "")

1

In [107]:
x1[0]

array([-0.131214  ,  0.40506428, -0.09965127,  0.108554  ,  0.0906961 ,
       -0.35504833,  0.18113686,  0.7251245 , -0.00347758,  0.01681055,
       -0.0676368 , -0.28989074,  0.08298634, -0.01099036,  0.06203691,
       -0.06011558,  0.31649387, -0.19716331, -0.0992918 , -0.5187703 ,
        0.21316051,  0.06425241,  0.0288099 , -0.37684548, -0.19620074,
       -0.13829866, -0.24751681, -0.21431142, -0.06735421,  0.24955131,
        0.13302392, -0.14974096,  0.00492808, -0.0781674 , -0.11948007,
        0.28996697, -0.03644804, -0.45349383, -0.01915752, -0.3871342 ,
        0.0815255 , -0.4998842 , -0.04040048,  0.10045863,  0.16813259,
       -0.06260138, -0.18454164, -0.06326258,  0.10669718,  0.18905354,
        0.22702166, -0.15061592,  0.0606267 ,  0.23812693, -0.33706   ,
        0.25434855,  0.2215723 ,  0.00992299, -0.29449177,  0.20862661,
       -0.0666228 ,  0.14744677, -0.09333467,  0.16745117,  0.05041554,
        0.3861928 ,  0.13372238, -0.11185363, -0.327495  ,  0.26539347,
       -0.18492223, -0.01256243,  0.19713157, -0.08752904,  0.17096311,
        0.03991216, -0.05924537,  0.02330257, -0.33901012,  0.12749758,
       -0.24630731,  0.1267409 , -0.26517773,  0.41524768,  0.04717572,
        0.01091176,  0.08341914,  0.3621623 ,  0.27976882, -0.03981943,
        0.07831441,  0.18454988, -0.01539636,  0.08687738,  0.28030917,
        0.02613361,  0.13082255, -0.34160587,  0.09997831,  0.02733184],
      dtype=float32)

In [108]:
y1=y.copy()

In [109]:
y1

array([2, 2, 2, ..., 0, 1, 0])

In [110]:
xtr, xtt, ytr, ytt=train_test_split(x1,y1, test_size=0.2, random_state=5)

In [111]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier()

In [112]:
rf.fit(xtr,ytr)

RandomForestClassifier()

In [113]:
yp=rf.predict(xtt)

In [114]:
print(accuracy_score(yp, ytt))

0.89375