In [ ]:
!unzip "/content/IMDB Dataset.csv.zip" -d "/content/"

Archive:  /content/IMDB Dataset.csv.zip
  inflating: /content/IMDB Dataset.csv

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/IMDB Dataset.csv')
df=df.iloc[:10000]
df

                                                 review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. <br /><br />The...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[10000 rows x 2 columns]

In [ ]:
df.isna().sum()

review       0
sentiment    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(17)

In [ ]:
df.drop_duplicates(inplace=True)

Preprocessing


*   lower casing
*   remove html tags
*   remove punctuation
*   Stop words
*   Stemming/lematization

In [ ]:
# To lowercase
df['review']= df['review'].str.lower()
df

                                                 review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production. <br /><br />the...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically there's a family where a little boy ...  negative
4     petter mattei's "love in the time of money" is...  positive
...                                                 ...       ...
9995  fun, entertaining movie about wwii german spy ...  positive
9996  give me a break. how can anyone say that this ...  negative
9997  this movie is a bad movie. but after watching ...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about film-making. shows the int...  positive

[9983 rows x 2 columns]

In [ ]:
# removing html tags
import re
def remove_html(text):
    pattern = re.compile('<.*?>')
    return pattern.sub('', text)

In [ ]:
df['review']=df['review'].apply(remove_html)
df

                                                 review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production. the filming tec...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically there's a family where a little boy ...  negative
4     petter mattei's "love in the time of money" is...  positive
...                                                 ...       ...
9995  fun, entertaining movie about wwii german spy ...  positive
9996  give me a break. how can anyone say that this ...  negative
9997  this movie is a bad movie. but after watching ...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about film-making. shows the int...  positive

[9983 rows x 2 columns]

In [ ]:
#Removing punctuation
import string
def remove_punc(text):
  return text.translate(str.maketrans('','', string.punctuation))

In [ ]:
df['review']=df['review'].apply(remove_punc)
df

                                                 review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production the filming tech...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically theres a family where a little boy j...  negative
4     petter matteis love in the time of money is a ...  positive
...                                                 ...       ...
9995  fun entertaining movie about wwii german spy j...  positive
9996  give me a break how can anyone say that this i...  negative
9997  this movie is a bad movie but after watching a...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about filmmaking shows the inten...  positive

[9983 rows x 2 columns]

In [ ]:
#removing stop words
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))

    words = text.split()

    filtered_words = [
        word for word in words
        if word.lower() not in stop_words
    ]

    return " ".join(filtered_words)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
df['review']=df['review'].apply(remove_stopwords)
df

                                                 review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production filming technique ...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically theres family little boy jake thinks...  negative
4     petter matteis love time money visually stunni...  positive
...                                                 ...       ...
9995  fun entertaining movie wwii german spy julie a...  positive
9996  give break anyone say good hockey movie know m...  negative
9997  movie bad movie watching endless series bad ho...  negative
9998  movie probably made entertain middle school ea...  negative
9999  smashing film filmmaking shows intense strange...  positive

[9983 rows x 2 columns]

In [ ]:
#from bs4 import BeautifulSoup

#def remove_html(text):
    #return BeautifulSoup(text, "html.parser").get_text(separator=" ")

In [ ]:
#df['review']=df['review']

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [ ]:
from nltk.stem import WordNetLemmatizer
wl=WordNetLemmatizer()

def lem(text):
  words=text.split()
  words=([wl.lemmatize(word)for word in words])
  return " ".join(words)

In [ ]:
df['review']=df['review'].apply(lem)
df['review'][0]

'one reviewer mentioned watching 1 oz episode youll hooked right exactly happened methe first thing struck oz brutality unflinching scene violence set right word go trust show faint hearted timid show pull punch regard drug sex violence hardcore classic use wordit called oz nickname given oswald maximum security state penitentary focus mainly emerald city experimental section prison cell glass front face inwards privacy high agenda em city home manyaryans muslim gangsta latino christian italian irish moreso scuffle death stare dodgy dealing shady agreement never far awayi would say main appeal show due fact go show wouldnt dare forget pretty picture painted mainstream audience forget charm forget romanceoz doesnt mess around first episode ever saw struck nasty surreal couldnt say ready watched developed taste oz got accustomed high level graphic violence violence injustice crooked guard wholl sold nickel inmate wholl kill order get away well mannered middle class inmate turned prison bitch due lack street skill prison experience watching oz may become comfortable uncomfortable viewingthats get touch darker side'

In [ ]:
x=df.drop('sentiment', axis=1)
y=df['sentiment']

In [ ]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

y=le.fit_transform(y)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.2, random_state=51)

In [ ]:
len(y_test)

1997

In [ ]:
#Using BOW or TFIDF

from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer()#in this we can give max_fetures=3000 like this, it will take most repeatable 3000 words/features to train the model
# we can alsso use ngrams but space will be exhausted because of exponential increase in features
# we can also use TF-IDF instead of Bow
x_train_bow=cv.fit_transform(x_train['review']).toarray()
x_test_bow=cv.transform(x_test['review']).toarray()

In [ ]:
from sklearn.naive_bayes import GaussianNB

model=GaussianNB()

In [ ]:
model.fit(x_train_bow, y_train)

GaussianNB()

In [ ]:
ypred=model.predict(x_test_bow)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
print(accuracy_score(ypred, y_test))

0.6359539308963446

In [ ]:
print(confusion_matrix(ypred, y_test))

[[729 444]
 [283 541]]

In [ ]:
print(classification_report(ypred, y_test))

              precision    recall  f1-score   support

           0       0.72      0.62      0.67      1173
           1       0.55      0.66      0.60       824

    accuracy                           0.64      1997
   macro avg       0.63      0.64      0.63      1997
weighted avg       0.65      0.64      0.64      1997

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier()

rf.fit(x_train_bow, y_train)

RandomForestClassifier()

In [ ]:
y_pred=rf.predict(x_test_bow)

print(accuracy_score(y_pred, y_test)*100)

84.77716574862293

# **Also Lets take user input and get output**

In [ ]:
# Take input
rw=input("Write your Review")
#to lowercase
rw=rw.lower()
#remove html
rw=remove_html(rw)
#remove punctuation
rw=remove_punc(rw)
#remove stopwords
rw=remove_stopwords(rw)
#lemmatize the words
rw=lem(rw)
# apply BOW
rw=cv.transform([rw])
#predict
rw=rf.predict(rw)

if rw[0]==1:
  print("Positive Review")
else:
  print("Negative Review")

Write your Reviewit was the worst movie i have ever seen very bad
Negative Review

Also We can train our Word2Vec Model for Text Vectorization instead of BOW or TF-IDF

In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.0)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 16.5 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
import gensim
import numpy as np
import nltk
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
data=[]

for word in df['review']:
  rs=sent_tokenize(word)
  for sent in rs:
    data.append(simple_preprocess(sent))

In [ ]:
len(data)

9983

In [ ]:
model=gensim.models.Word2Vec(
    window=5,
    min_count=2
)

In [ ]:
model.build_vocab(data)

In [ ]:
model.train(data, total_examples=model.corpus_count, epochs=model.epochs)

(5410335, 5890400)

In [ ]:
def doc_vector(doc):
  doc=[word for word in doc.split() if word in model.wv.index_to_key]
  return np.mean(model.wv[doc], axis=0)

In [ ]:
doc_vector(df['review'].values[0])

In [ ]:
x=[]
for doc in df['review'].values:
  x.append(doc_vector(doc))

In [ ]:
len(x)

9983

so now we get x and y is there, fit ml model to it