In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('/content/spam.csv', encoding='latin-1')
df

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [7]:
df.drop(df[['Unnamed: 2',	'Unnamed: 3',	'Unnamed: 4']], axis=1, inplace=True)

In [8]:
df

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [16]:
df.isna().sum()

v1    0
v2    0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.drop_duplicates(inplace=True)

In [23]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

In [24]:
df['v1']=le.fit_transform(df['v1'])
df

      v1                                                 v2
0      0  go until jurong point crazy available only in ...
1      0                            ok lar joking wif u oni
2      1  free entry in 2 a wkly comp to win fa cup fina...
3      0        u dun say so early hor u c already then say
4      0  nah i dont think he goes to usf he lives aroun...
...   ..                                                ...
5567   1  this is the 2nd time we have tried 2 contact u...
5568   0                will ì b going to esplanade fr home
5569   0  pity  was in mood for that soany other suggest...
5570   0  the guy did some bitching but i acted like id ...
5571   0                          rofl its true to its name

[5142 rows x 2 columns]

In [25]:
df['v2']=df['v2'].str.lower()
df

      v1                                                 v2
0      0  go until jurong point crazy available only in ...
1      0                            ok lar joking wif u oni
2      1  free entry in 2 a wkly comp to win fa cup fina...
3      0        u dun say so early hor u c already then say
4      0  nah i dont think he goes to usf he lives aroun...
...   ..                                                ...
5567   1  this is the 2nd time we have tried 2 contact u...
5568   0                will ì b going to esplanade fr home
5569   0  pity  was in mood for that soany other suggest...
5570   0  the guy did some bitching but i acted like id ...
5571   0                          rofl its true to its name

[5142 rows x 2 columns]

In [26]:
import string

def remove_punc(text):
  return text.translate(str.maketrans(' ', ' ', string.punctuation))

In [27]:
df['v2']=df['v2'].apply(remove_punc)
df

      v1                                                 v2
0      0  go until jurong point crazy available only in ...
1      0                            ok lar joking wif u oni
2      1  free entry in 2 a wkly comp to win fa cup fina...
3      0        u dun say so early hor u c already then say
4      0  nah i dont think he goes to usf he lives aroun...
...   ..                                                ...
5567   1  this is the 2nd time we have tried 2 contact u...
5568   0                will ì b going to esplanade fr home
5569   0  pity  was in mood for that soany other suggest...
5570   0  the guy did some bitching but i acted like id ...
5571   0                          rofl its true to its name

[5142 rows x 2 columns]

In [28]:
#removing stop words
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))

    words = text.split()

    filtered_words = [
        word for word in words
        if word.lower() not in stop_words
    ]

    return " ".join(filtered_words)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [29]:
df['v2']=df['v2'].apply(remove_stopwords)
df

      v1                                                 v2
0      0  go jurong point crazy available bugis n great ...
1      0                            ok lar joking wif u oni
2      1  free entry 2 wkly comp win fa cup final tkts 2...
3      0                u dun say early hor u c already say
4      0        nah dont think goes usf lives around though
...   ..                                                ...
5567   1  2nd time tried 2 contact u u å£750 pound prize...
5568   0                        ì b going esplanade fr home
5569   0                        pity mood soany suggestions
5570   0  guy bitching acted like id interested buying s...
5571   0                                     rofl true name

[5142 rows x 2 columns]

In [33]:
import nltk
from nltk import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [34]:
wl=WordNetLemmatizer()
def lemmatize(text):
  text=text.split()
  text=[wl.lemmatize(word, pos='v') for word in text]
  return ' '.join(text)

In [35]:
df['v2']=df['v2'].apply(lemmatize)

In [36]:
x=df['v2']
y=df['v1']

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [38]:
xtr, xtt, ytr, ytt=train_test_split(x,y, test_size=0.2, random_state=5)

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf=TfidfVectorizer()

xtrain=tf.fit_transform(xtr).toarray()
xtest=tf.transform(xtt).toarray()

In [43]:
gb=GaussianNB()
mb=MultinomialNB()
bb=BernoulliNB()

In [45]:
gb.fit(xtrain,ytr)
y1=gb.predict(xtest)

In [47]:
mb.fit(xtrain, ytr)
y2=mb.predict(xtest)

In [46]:
bb.fit(xtrain, ytr)
y3=bb.predict(xtest)

In [48]:
from sklearn.metrics import accuracy_score

In [51]:
print(f"GaussianNB: {accuracy_score(y1,ytt)*100:.2f}%")
print(f"MultinomialNB: {accuracy_score(y2,ytt)*100:.2f}%")
print(f"BernouliNB: {accuracy_score(y3,ytt)*100:.2f}%")

GaussianNB: 87.95%
MultinomialNB: 95.34%
BernouliNB: 96.02%